version: '3'
services:
  bookshelf_db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: book
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/initdb.d/env/dev/:/docker-entrypoint-initdb.d
  bookshelf_db_test:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: book
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/initdb.d/env/test/:/docker-entrypoint-initdb.d

